hmcts/probate-submit-service

gradle/wrapper/gradle-wrapper.properties
src/main/java/uk/gov/hmcts/probate/services/submit/ApplicationConfig.java
src/main/java/uk/gov/hmcts/probate/services/submit/Registry.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/PersistenceClient.java
src/main/java/uk/gov/hmcts/probate/services/submit/controllers/SubmitController.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/SequenceService.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/SubmitService.java
src/main/resources/application.yml
src/test/java/uk/gov/hmcts/probate/services/submit/clients/PersistenceClientTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/controllers/SubmitControllerTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/services/SequenceServiceTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/services/SubmitServiceTest.java
src/test/resources/registryData.json

Pro 2407 alternate submissions between registries

---

src/main/java/uk/gov/hmcts/probate/services/submit/Registry.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/SequenceService.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/SubmitService.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapperTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/services/SequenceServiceTest.java
src/test/resources/registryData.json

- Include registry location and application type in the CCDData
- Refactor code to use registryData ObjectNode instead of sequenceNumber
- Refactor tests to account for new data object
```
[ ] Yes
[ ] No
```

PRO-2390: Include new fields in the CCDMapper class

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/Client.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/MailClient.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/MailMessageBuilder.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/PersistenceClient.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/SequenceService.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/SubmitService.java
src/main/resources/application.properties
src/main/resources/application.yml
src/main/resources/templates/email-template.html
src/test/java/uk/gov/hmcts/probate/services/submit/clients/MailClientTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/MailMessageBuilderTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/PersistenceClientTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/services/SequenceServiceTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/services/SubmitServiceTest.java
src/test/resources/registryData.json

Ensure that emails are sent to correct Registry based on the Round Robin approach.
Re-submit will be implemented in a separate ticket.
JIRA Ticket:
https://tools.hmcts.net/jira/browse/PRO-2410
```
[ ] Yes
[ ] No
```

Pro 2410 generated email sent to correct registry

---

build.gradle

PRO-2868: update dependency check plugin

---

src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/SubmitServicePersistenceClientTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/SubmitServiceSubmitControllerTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/TestUtils.java

- Functional tests for both submit and resubmit
- Refactor hierarchy of Test classes -> to avoid code reuse (populate test data function)
- Add submitHeaders method as the headers for submissions differ from other API's
```
[ ] Yes
[ ] No
```

PRO-2762: Implement functional tests for SubmitController

---

src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/SubmitServicePersistenceClientTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/TestUtils.java

PRO-2762: Fix broken Jenkins build by fixing previous merged PR

---

src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/SubmitServicePersistenceClientTests.java
src/functionalTest/resources/json/formData.json

- Obtain the submissionId from the post response
```
[ ] Yes
[ ] No
```

PRO-2762: Fix tests that were failing in the Azure environments

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapperTest.java
src/test/resources/ccdNotApplyingExecutors.json
src/test/resources/formPayload.json

Pro 3010 ccd null pointer exception

---

build.gradle
src/lib/AI-Agent.xml
src/main/java/uk/gov/hmcts/probate/insights/AppInsights.java
src/main/resources/application.yml

- Add AI-Agent xml file
- Make changes to build.gradle
- Refactor AppInsights class
- Add logging config to application.yml
```
[ ] Yes
[ ] No
```

PRO-2845: Implement Application Insights for the Submit Service

---

src/main/java/uk/gov/hmcts/probate/security/SecurityUtils.java

@nigeldunne @reddy1praveen please merge this.
```
[ ] Yes
[ ] No
```

add log message with token

---

build.gradle
src/test/java/uk/gov/hmcts/probate/services/submit/services/GitCommitInfoEndpointTest.java

https://tools.hmcts.net/jira/browse/PRO-2960
Change to fix a test after a merge conflict issue resulted in the wrong information being taken.
```
[ ] Yes
[x] No
```

PRO-2960: Correction to merge issue from CNP branch to develop.

---

Dockerfile
Jenkinsfile
build.gradle

Corrected Docker and tactical fix

---

src/functionalTest/java/uk/gov/hmcts/probate/functional/IntegrationTestBase.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/SubmitServicePersistenceClientTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/SubmitServiceSubmitControllerTests.java
src/test/resources/formData.json

PRO-2762: Add a tearDown function to run after Persistent Client tests

---

infrastructure/demo.tfvars

corrected demo url

---

src/contractTest/java/uk/gov/hmcts/probate/contract/SolCcdServiceAuthTokenGenerator.java
src/contractTest/java/uk/gov/hmcts/probate/contract/util/ContractTestUtils.java

change string to int

---

src/main/java/uk/gov/hmcts/probate/SubmitApplication.java
src/main/java/uk/gov/hmcts/probate/services/submit/health/SubmitHealthConfiguration.java

- Exclude ServiceAuthHealthIndicator which is included in the client jar.
- Added serviceAuthHealthIndicator
```
[ ] Yes
[x] No
```

Fixed service auth health endpoint.

---

src/contractTest/resources/json/failure.pa.ccd.json
src/contractTest/resources/json/success.pa.ccd.json
src/functionalTest/resources/json/submitData.json

PRO:3226 fix contract tests

---

infrastructure/preview.tfvars

Pro fix preview urls

---

src/main/resources/application.yml

https://tools.hmcts.net/jira/browse/PRO-3345
```
[ ] Yes
[x] No
```

PRO-3345 : Added Manchester registry

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java

PRO-2344: fix for merge issue

---

infrastructure/main.tf
infrastructure/output.tf
infrastructure/variables.tf

Moved to Central Vault

---

infrastructure/main.tf

[PREVIEW] Moved to azure vault

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java
src/main/resources/application.yml
src/main/resources/messages.properties
src/main/resources/templates/email-template.html
src/test/java/uk/gov/hmcts/probate/services/submit/clients/MailMessageBuilderTest.java
src/test/resources/ccdApplyingExecutors.json
src/test/resources/formPayload.json
src/test/resources/submitdata.json

https://tools.hmcts.net/jira/browse/PRO-3376
-updating email template with executor alias reason fields.
-update CCD mapper

[PREVIEW] Pro 3376 executor alias submit 

---

src/test/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapperTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/model/CcdCaseResponseTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/model/FormDataTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/model/SubmitDataTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/services/SubmitServiceTest.java
src/test/resources/ccdCaseResponseEmptyPayments.json
src/test/resources/formDataModel.json
src/test/resources/submitdata.json

Increased test coverage.
```
[ ] Yes
[X] No
```

PRO-4027: Increased test coverage.

---

build.gradle
src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataClient.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/MailClient.java
src/main/java/uk/gov/hmcts/probate/services/submit/model/PaymentResponse.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/SubmitService.java
src/test/java/uk/gov/hmcts/probate/services/submit/model/PaymentResponseTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/services/SubmitServiceTest.java

- Used "getAmount", as it correctly converts the values to pence.
- isAmountMissing just checks if the field exists in the JSON, to avoid nullpointer exceptions.
```
[ ] Yes
[X] No
```

[PREVIEW] PRO-4116: Fixed 50p payment issue to ensure payment info is submitted to CCD

---

config/owasp/suppressions.xml

PRO-3488: supress sl4j vulnerability

---

build.gradle
docker/docker-compose-with-ccd-pa.yml
src/main/java/uk/gov/hmcts/probate/services/submit/core/CaseTypeConfiguration.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/proccessors/impl/CreateCaseSubmissionsProcessor.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/SequenceService.java
src/main/java/uk/gov/hmcts/probate/services/submit/validation/validator/CaveatValidator.java
src/test/java/uk/gov/hmcts/probate/services/submit/core/CreateCaseSubmissionsProcessorTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/validation/validator/CaveatValidatorTest.java

https://tools.hmcts.net/jira/browse/PRO-4152
Update submit case with registry location for v2 submissions service
```
[ ] Yes
[ X] No
```

Pro 4152 update v2 submissions call for allocation of registry

---

Jenkinsfile_nightly
security.sh

set up probate submit service security scan

---

src/main/java/uk/gov/hmcts/probate/services/submit/model/SubmitException.java

https://tools.hmcts.net/jira/browse/PRO-4920
Fix bug raised by Sonar Scan
```
[ ] Yes
[ X] No
```

PRO-4920:  Fix bug highlighted by Sonar Scan

---

infrastructure/aat.tfvars
infrastructure/demo.tfvars
infrastructure/main.tf
infrastructure/prod.tfvars
infrastructure/saat.tfvars
infrastructure/sandbox.tfvars
infrastructure/sprod.tfvars
infrastructure/variables.tf

Added variables for correct auth and idam urls
```
[ ] Yes
[X] No
```

PRO-4244: Added correct authorisation URLs in infrastructure

---

docker/docker-compose-with-ccd-pa.yml
src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java
src/test/resources/ccdApplyingExecutors.json

Applying additional exec names need to be swapped for correct placement on grants

PRO-4924: corrected name mapping for additional execs

---

kubernetes/config.aat.yaml

PRO-5003: Test SIDAM

---

infrastructure/aat.tfvars

PRO-5003: SIDAM test

---

infrastructure/aat.tfvars

PRO-5003: SIDAM Testing

---

kubernetes/config.aat.yaml

Pro 5003 sidam testing pr

---

src/test/java/uk/gov/hmcts/probate/services/submit/services/SequenceServiceTest.java

added test for 12.5, 12.5, 75% Oxf, Birm, Man ratio

PRO-4078: add correct test for registry ratios

---

src/main/java/uk/gov/hmcts/probate/services/submit/Registry.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/SequenceService.java
src/test/java/uk/gov/hmcts/probate/services/submit/services/SequenceServiceTest.java

https://tools.hmcts.net/jira/browse/PRO-5041
Remove capitalisation of Registry name as business requires it all lower case
```
[ ] Yes
[X] No
```

PRO-5041: Remove capitalisation of Registry name

---

infrastructure/prod.tfvars

Update Capacity to 2 prod

---

build.gradle
config/owasp/suppressions.xml
kubernetes/config.aat.yaml
src/functionalTest/java/uk/gov/hmcts/probate/functional/SubmitServicePersistenceClientTests.java
src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesController.java
src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/DraftsController.java
src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/PaymentsController.java
src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/SubmissionsController.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/CaseTypeConfiguration.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/proccessors/AbstractSubmissionsProcessor.java

change from applicant email to applicationId
[ ] Yes
[ x] No
```

PRO-5001 change from applicant email to applicationId

---

build.gradle

change to commons ver 27
[ ] Yes
[ x] No
```

PRO-5089: change to commons ver 27

---

infrastructure/sprod.tfvars

PRO-4761: update auth_idam_client_baseurl in sprod.tfvars

---

build.gradle
config/owasp/suppressions.xml

add suppressions

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java
src/main/resources/application.yml
src/test/resources/ccdAddresses.json
src/test/resources/ccdApplyingExecutors.json
src/test/resources/formPayload.json

PRO-3173: submit addtional address fields
```
[ ] Yes
[ x] No
```

PRO-3173: submit addtional address fields

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java

PRO-3173: remove redundant variable
```
[ ] Yes
[ x] No
```

PRO-3173: remove redundant variable

---

src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/ControllerProviderTest.java
src/pactTest/resources/application.properties

- [ x] commit messages are meaningful and follow good commit message guidelines
- [x ] README and other documentation has been updated / added (if needed)
- [ x] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ x] No
```

FixPactVersion in provider tests

---

build.gradle
charts/probate-submit-service/Chart.yaml
charts/probate-submit-service/requirements.yaml

https://tools.hmcts.net/jira/browse/PRO-4999
```
[ ] Yes
[x ] No
```

update j chart, add springboot-starter

---

config/owasp/suppressions.xml
infrastructure/aat.tfvars

increase capacity

---

charts/probate-submit-service/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/PRO-5645
Remove SMTP infrastructure code from charts.
```
[x] Yes
[ ] No
```

PRO-5645: Remove SMTP infrastructure code

---

src/main/resources/application.yml

Add additional intestacy fields to submitted data to CCD
```
[ ] Yes
[ ] No
```

PRO-4775 Intestacy definitions update

---

build.gradle
config/owasp/suppressions.xml

Pro 5643 upgrade owasp

---

build.gradle

Owasp update test build

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapperTest.java
src/test/resources/success.pa.ccd.json

https://tools.hmcts.net/jira/browse/PRO-5356
Default the 'is paper form?' field to 'No' in CCD
```
[ ] Yes
[x] No
```

Pro 5356 default pa cases to digital when submitting to ccd

---

build.gradle
charts/probate-submit-service/values.preview.template.yaml
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java

https://tools.hmcts.net/jira/browse/PRO-5556
Default "is paper form?" to "No" on CCD for caveats
```
[ ] Yes
[x] No
```

Pro 5556 default caveats cases to digital

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java
src/main/resources/application.yml
src/test/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapperTest.java
src/test/resources/ccdStatementOfTruth.json
src/test/resources/formPayload.json

https://tools.hmcts.net/jira/browse/PRO-5851
Save SoT pdf link to CCD
```
[ ] Yes
[x] No
```

Pro 5850 submit statement of truth

---

Jenkinsfile_CNP
charts/probate-submit-service/Chart.yaml
charts/probate-submit-service/requirements.yaml
charts/probate-submit-service/values.preview.template.yaml
config/owasp/suppressions.xml
infrastructure/output.tf

try with latest CCD only

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataMapper.java

https://tools.hmcts.net/jira/browse/PRO-5924
Fix bug which prevents submitting without SOT field. 
```
[ ] Yes
[x] No
```

Pro 5924 fix sot bug 2

---

charts/probate-submit-service/values.yaml

update docker repo

---

Jenkinsfile_CNP
charts/probate-submit-service/values.aat.template.yaml
charts/probate-submit-service/values.preview.template.yaml
src/main/resources/bootstrap.yaml

add secrets

---

charts/probate-submit-service/values.aat.template.yaml

disable ccd

---

charts/probate-submit-service/values.aat.template.yaml

 add aadIdentityName: probate

---

Dockerfile
Jenkinsfile_CNP
build.gradle
charts/probate-submit-service/Chart.yaml
charts/probate-submit-service/requirements.yaml
charts/probate-submit-service/values.aat.template.yaml
charts/probate-submit-service/values.preview.template.yaml
charts/probate-submit-service/values.yaml
infrastructure/main.tf
src/README.md
src/main/java/uk/gov/hmcts/probate/SubmitApplication.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/CoreCaseDataClient.java
src/main/java/uk/gov/hmcts/probate/services/submit/controllers/GenericExceptionHandler.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/DraftServiceImpl.java
src/main/resources/application.yml
src/main/resources/bootstrap.yaml
src/test/java/uk/gov/hmcts/probate/services/submit/controllers/SubmitControllerTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/services/SequenceServiceTest.java

PRO-1234: Test

---

Jenkinsfile_CNP
infrastructure/perftest.tfvars

Enable AKS build in AAT and perftest

---

Dockerfile
build.gradle
web.config

upgrade jackson version

---

Jenkinsfile_CNP
build.gradle

revert jakson

---

Dockerfile
web.config

Upgrade appinsights to fix instrumentation issue.

---

Jenkinsfile_CNP

ASE To AKS Migration

---

charts/probate-submit-service/Chart.yaml
charts/probate-submit-service/values.yaml
src/main/resources/application.yml

Added logs setting

---

build.gradle

https://tools.hmcts.net/jira/browse/PRO-6545
Not updating when executor has disagreed to declaration
```
[ ] Yes
[x] No
```

PRO-6545: Not updating when executor has disagreed to declaration

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdClientApi.java
src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesController.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/CasesServiceImpl.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/CasesService.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/CoreCaseDataService.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdClientApiTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesControllerTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/core/CasesServiceImplTest.java

Pro 6602 migration fixes

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdClientApi.java

PRO-6602: Fix duplicate cases issue

---

src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesController.java
src/main/resources/application.yml

PRO-6602: Increase timeouts for CCD api calls

---

build.gradle

https://tools.hmcts.net/jira/browse/PRO-6683
Add submit warning to invite
```
[ ] Yes
[x] No
```

PRO-6683: Update commons version

---

build.gradle

PRO-6548: Update commons version for postcode fix

---

config/owasp/suppressions.xml

PRO-6786: Add suppressions for dependency check

---

config/owasp/suppressions.xml

PRO-6786: Add yet more suppressions for dependency check

---

build.gradle

WLA-22: Update commons for alias reason mappings fix

---

build.gradle

WLA-65: Release commons

---

build.gradle

PRO-6387: Add N/A rules for iht fields

---

build.gradle

https://tools.hmcts.net/jira/browse/PRO-6885
Update commons version for caveats prod issue where dob is not known. 
```
[ ] Yes
[x] No
```

PRO-6885: Update commons version

---

Jenkinsfile_CNP
build.gradle
charts/probate-submit-service/Chart.yaml
src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseContentBuilder.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseResponseBuilder.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdClientApi.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdElasticSearchQueryBuilder.java
src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesController.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/CaveatExpiryServiceImpl.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/CaveatExpiryService.java
src/main/java/uk/gov/hmcts/probate/services/submit/services/CoreCaseDataService.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseContentBuilderTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseResponseBuilderTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdClientApiTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdElasticSearchQueryBuilderTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesControllerTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/core/CaveatExpiryServiceImplTest.java

PRO-5170: expire caveats

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseDetailsToCaseDataMapper.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseResponseBuilder.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/CaveatExpiryServiceImpl.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseResponseBuilderTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/core/CaveatExpiryServiceImplTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/core/mapper/CaseDetailsToCaseDataMapperTest.java

Corrected null caveat data on auto expiry

PRO-5170: corrected null caveat data on expiry

---

src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseDetailsToCaseDataMapper.java
src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseResponseBuilder.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/CaveatExpiryServiceImpl.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CaseResponseBuilderTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/core/CaveatExpiryServiceImplTest.java
src/test/java/uk/gov/hmcts/probate/services/submit/core/mapper/CaseDetailsToCaseDataMapperTest.java

Do not use ImmutableMap for CCD responses

Pro 5170 find expired caveats

---

Jenkinsfile_CNP
build.gradle
src/main/java/uk/gov/hmcts/probate/services/submit/core/RegistryService.java
src/test/java/uk/gov/hmcts/probate/services/submit/core/RegistryServiceTest.java

Merge to demo from master

---

build.gradle

updated commons for caveatData missing field

PRO-1234: added caveatData attr to commons

---

build.gradle

PRO-1234: upgraded commons

---

Jenkinsfile_CNP

Unbreak build to prod for 20 02 2020

UnbreakBuildForProd2002

---

config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdElasticSearchQueryBuilder.java
src/test/java/uk/gov/hmcts/probate/services/submit/clients/v2/ccd/CcdElasticSearchQueryBuilderTest.java

fix caveat auto expiry max rows

PRO-7083: fixed cave auto exp max rows

---

build.gradle

PRO-6841: Reference new commons version

---

Jenkinsfile_CNP

Moving to AKS on AAT

---

build.gradle

upgraded commons to allow app recvd to save as doc on case

PRO-7187: upraded commons

---

build.gradle
config/owasp/suppressions.xml
src/test/resources/files/v2/intestacyGrantOfRepresentation.json
src/test/resources/files/v2/intestacyGrantOfRepresentation_caseDetails.json

https://tools.hmcts.net/jira/browse/PRO-7229
Update to probate commons to include pcqId 1.0.6.1_PRO-7229.
```
[ ] Yes
[x] No
```

PRO-7229 Update probate-commons lib to pickup pcqId

---

Jenkinsfile_CNP
config/owasp/suppressions.xml
src/main/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesController.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/CasesServiceImpl.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/ValidationServiceImpl.java
src/test/java/uk/gov/hmcts/probate/services/submit/core/ValidationServiceImplTest.java

PRO-7776: added logging

---

charts/probate-submit-service/Chart.yaml
charts/probate-submit-service/values.yaml
src/main/resources/application.properties

PRO-7787: corrected ccd log level

---

src/main/java/uk/gov/hmcts/probate/services/submit/core/CasesServiceImpl.java
src/main/java/uk/gov/hmcts/probate/services/submit/core/ValidationServiceImpl.java

Pro 7776 add logging

---

build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/PRO-7904
Upgrade submit service from gradle 4.4.1 to gradle 5+
```
[ ] Yes
[x] No
```

PRO-7904: Add gradle 5 to wrapper

---

.travis.yml
Dockerfile
build.gradle

https://tools.hmcts.net/jira/browse/PRO-7812
Java 11 version upgrade changes
Jacoco version updated
removed findbugs
```
[ ] Yes
[X] No
```

PRO-7812 Java11 upgrade changes

---

README.md
build.gradle

https://tools.hmcts.net/jira/browse/PRO-7826
the pie chart for the serenity report isn't showing up , these changes are to fix it
```
[ ] Yes
[ X ] No
```

PRO-7826 Fix Serenity report display

---

src/functionalTest/java/uk/gov/hmcts/probate/functional/TestRetryRule.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/cases/GetCasesTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/cases/SaveCaseTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/cases/ValidateCasesTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/payments/CaveatsPaymentTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/payments/GrantOfRepresentationPaymentTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/util/TestUtils.java

https://tools.hmcts.net/jira/browse/DTSPB-494
Add retries to failing tests 
```
[ ] Yes
[x] No
```

DTSPB-494: Add retries to tests

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-631
Changes for owasp version upgrade
```
[ ] Yes
[ X ] No
```

DTSPB-631 changes for owasp version upgrade

---

build.gradle

DTSPB-786: upgraded ccd client api

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-111
Update Commons to 1.1.0.2
```
[ ] Yes
[x] No
```

Update Commons to 1.1.0.2

---

config/owasp/suppressions.xml
src/functionalTest/java/uk/gov/hmcts/probate/functional/cases/GetCasesTests.java
src/functionalTest/java/uk/gov/hmcts/probate/functional/cases/SaveCaseTests.java

- [X ] tests have been updated / new tests has been added (if needed)
```
[ ] Yes
[ X] No
```

TA-278 Test added to improve the coverage.

---

build.gradle
config/owasp/suppressions.xml
src/functionalTest/resources/json/gop.multipleExecutors.full.json
src/functionalTest/resources/json/gop.multipleExecutors.partial.json
src/functionalTest/resources/json/gop.paymentInitiated.json
src/functionalTest/resources/json/gop.singleExecutor.full.json
src/functionalTest/resources/json/gop.singleExecutor.partial.json
src/functionalTest/resources/json/intestacy.full.json
src/functionalTest/resources/json/intestacy.partial.json

https://tools.hmcts.net/jira/browse/DTSPB-529
https://tools.hmcts.net/jira/browse/DTSPB-535
https://tools.hmcts.net/jira/browse/DTSPB-534
New death cert processes
```
[ ] Yes
[x] No
```

Point to commons 1.1.0.DTSPB-529-new-death-cert-process

---

build.gradle
config/owasp/suppressions.xml
src/main/resources/application.yml

DTSPB-1340-upgrade-ccd-verrsion
DTSPB-1340-upgrade-ccd-verrsion
```
[ ] Yes
[x] No
```

DTSPB-1340-upgrade-ccd-verrsion

---

charts/probate-submit-service/Chart.yaml
charts/probate-submit-service/requirements.yaml

https://tools.hmcts.net/jira/browse/DTSPB-891
Java chart version update
```
[ ] Yes
[ X ] No
```

DTSPB-891 Java chart version update

---

build.gradle
config/owasp/suppressions.xml

DTSPB-1233
update dependency versions and close bumping prs
```
[ ] Yes
[ ] No
```

DTSPB-1233 Updated dependencies and rewritten suppression file

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1647
https://tools.hmcts.net/jira/browse/DTSPB-1543
Bouncycastle dependency suppression
```
[ ] Yes
[X ] No
```

DTSPB-1647 Fix Bouncycastle dependency suppression

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1650
https://tools.hmcts.net/jira/browse/DTSPB-1652
changes to resolve supressions
[ ] Yes
[X ] No

DTSPB-1650+52 resolve suppressions for beanutils and httpclient

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1649
CVE resolution
[ ] Yes
[X ] No

DTSPB-1649 tomcat related suppressions resolution

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1686
CVE resolution
[ ] Yes
[ X ] No

DTSPB-1686 Resolve CVE-2021-22112 suppression

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-1651
added junit upper version as a transitive dependencies to resolve suppression
[ ] Yes
[ X ] No

Resolve CVE-2020-1520 suppression

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-1775
update commons version
```
[ ] Yes
[X] No
```

DTSPB-1775 updated commons version

---

charts/probate-submit-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-1843
Update the JAVA api version
```
[ ] Yes
[X] No
```

DTSPB-1843 Update the java chart version

---

build.gradle

n/a
fix the failing dependency suppression 
```
[ ] Yes
[ X] No
```

Fix failing dependency suppression

---

build.gradle

DTSPB-1818 upgrade commons jitpack
DTSPB-1818 upgrade commons jitpack
```
[ ] Yes
[x] No
```

DTSPB-1818 upgrade commons jitpack

---

audit.json
security.sh

Create audit.json, picked up by glue via security.sh Using dummy entries in audit.json for now.

Update glue config

---

security.sh

https://tools.hmcts.net/jira/browse/DTSPB-1932
fix zap security scan issues
```
[ ] Yes
[ X ] No
```

DTSPB-1932 Fix nightly build

---

security.sh

Update security  config

---

security.sh

fixing security scan issue

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-1526
bump probate-commons
```
[ ] Yes
[x] No
```

Dtspb 1526 commons

---

build.gradle

prod issue 
lev commons changes was pushed as a prep but lev is not live today 
```
[ ] Yes
[ X ] No
```

Rollback Commons version as lev not live yet

---

Jenkinsfile_CNP

https://tools.hmcts.net/jira/browse/DTSPB-2020
code changes to sync all branches to master with every deployment
[ ] Yes
[ X ] No

DTSPB-2020 Sync All env to master with every commit

---

build.gradle

n/a
Fix the Probate-pact-commons library version and jitpack
```
[ ] Yes
[ ] No
```

Fix the Probate-pact-commons library version and jitpack

---

build.gradle
suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-2095
Fix CVE-2021-22118
[ ] Yes
[ X ] No

Fix CVE-2021-22118

---

Jenkinsfile_CNP

commit to build new image
```
[ ] Yes
[ X ] No
```

Commit to build a new jar

---

security.sh

Dtspb 2168 fix nightly

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2176
```
[ ] Yes
[X ] No
```

fix open dependabot PRs

---

build.gradle

DTSPB-2221
Fix nightly failures
[ ] Yes
[X ] No

DTSPB-2221 Tomcat dependency upgrade

---

Jenkinsfile_nightly
build.gradle
config/fortify-client.properties
src/test/resources/logback.xml

https://tools.hmcts.net/jira/browse/DTSPB-2209
```
[ ] Yes
[ X ] No
```

Fortify integration to nightly

---

suppressions.xml

N/A
Suppress CVE until spring boot upgrade
```
[ ] Yes
[x] No
```

Suppress CVE until spring boot upgrade

---

charts/probate-submit-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-2276
- Bump chart.yaml java version to 3.6.0
```
[ ] Yes
[x] No
```

DTSPB-2276 - Bump chart.yaml java version to 3.6.0

---

build.gradle

New Tag for commons to fix TC issue

---

build.gradle

Commons changes for will and codicils condition
```
[ ] Yes
[ ] No
```

Commons changes for will and codicils condition

---

suppressions.xml

Suppress depdendency warning
```
[ ] Yes
[x] No
```

Suppress depdendency warning

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2482
Legal statement change for excepted estate
```
[ ] Yes
[x] No
```

DTSPB-2482: Legal statement change for excepted estate

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2493
Make ihtFormCompletedOnline optional
```
[ ] Yes
[x] No
```

DTSPB-2493: Make ihtFormCompletedOnline optional

---

charts/probate-submit-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-2584
```
[ ] Yes
[ x ] No
```

DTSPB-2584: Resolve the below deprecated warning form Java repos

---

charts/probate-submit-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSPB-2642
[ ] Yes
[ X ] No

DTSPB-2642 Java chart version update

---

Jenkinsfile_CNP
build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-2616
```
[ ] Yes
[x] No
```

DTSPB-2616 Fix Generating Serenity Report

---

security.sh

https://tools.hmcts.net/jira/browse/DTSPB-2645
```
[ ] Yes
[ X ] No
```

DTSPB-2645 Security Scan Fix

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-699
Bump probate-commons
```
[ ] Yes
[x] No
```

DTSPB-699: bump commons

---

build.gradle

https://tools.hmcts.net/jira/browse/DTSPB-1493
point to new commons version
[ ] Yes
[ ] No

DTSPB-1493 point to new commons version

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-2689
```
[ ] Yes
[x] No
```

DTSPB-2689 remove Jackson databind from suppressions.xml

---

build.gradle

Dtspb 2544 pp notorial access

---

build.gradle

DTSPB-2781: commons upgrade

---

build.gradle
suppressions.xml

DTSPB-2705 dob equals dod

---

build.gradle
suppressions.xml

DTSPB-2081: resolved cve

---

suppressions.xml

DTSPB-2896
```
[ ] Yes
[x] No
```

DTSPB-2896 suppress log4j cve

---

suppressions.xml

DTSPB-2940
```
[ ] Yes
[x] No
```

DTSPB-2940 CVE

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3033
```
[ ] Yes
[X ] No
```

DTSPB-3033 Supress CVE-2022-38752

---

build.gradle
suppressions.xml

DTSPB-2997 hand off flag

---

suppressions.xml

DTSPB-3261
```
[ ] Yes
[x] No
```

DTSPB-3261 CVE suppressions

---

.dependabot/config.yml
renovate.json

https://tools.hmcts.net/jira/browse/DTSPB-3291
Deleted .dependabot directory and added / updated renovate.json file to match probate-back-office setup.
```
[ ] Yes
[x] No
```

Replacing Dependabot with Renovate

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3390
```
[ ] Yes
[ ] No
```

DTSPB-3390: added suppressions

---

build.gradle
charts/probate-submit-service/Chart.yaml

Renovate group upgrade 7/3/23

---

Dockerfile

https://tools.hmcts.net/jira/browse/DTSPB-3523
update dockerfile java base image
```
[ ] Yes
[ x] No
```

DTSPB-3523 update dockerfile java base image

---

build.gradle

DTSPB-3617
address CVE-2023-20883
```
[ ] Yes
[ x] No
```

DTSPB-3617 address CVE-2023-20883

---

suppressions.xml

https://tools.hmcts.net/jira/browse/DTSPB-3766
```
[ ] Yes
[X] No
```

DTSPB-3766 Suppress CVE

---

renovate.json

https://tools.hmcts.net/jira/browse/DTSPB-3760
```
[ ] Yes
[ x] No
```

DTSPB: 3760 updated the renovate.json and removed enable managers .

---

Jenkinsfile_nightly
gradlew.bat

https://tools.hmcts.net/jira/browse/DTSPB-3967

DTSPB-3967 add fortify scan

---

build.gradle
charts/probate-submit-service/Chart.yaml
charts/probate-submit-service/values.yaml

https://tools.hmcts.net/jira/browse/DTSPB-4582
```
[ ] Yes
[X] No
```

DTSPB-4582 Point PR

---

build.gradle

DTSPB-4700
update commons version
```
[ ] Yes
[x] No
```

DTSPB-4700 update commons version

---

.github/renovate.json
build.gradle
src/main/java/uk/gov/hmcts/probate/SubmitApplication.java
src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/CasesControllerProviderTest.java
src/pactTest/java/uk/gov/hmcts/probate/services/submit/controllers/v2/SubmissionsControllerProviderTest.java

DTSPB-4854
fix pipeline and set renovate schedule
```
[ ] Yes
[x] No
```

DTSPB-4854 fix pipeline and set renovate schedule

---

build.gradle

DTSPB-4661 
bump commons
```
[ ] Yes
[x] No
```

DTSPB-4661 bump commons
